export const ADD_RESULTS = "ADD_RESULTS";
export const RESULTS_LOADING = "RESULTS_LOADING";
export const RESULTS_FAILED = "RESULTS_FAILED";
export const ADD_HOMERESULTS = "ADD_HOMERESULTS";
export const HOMERESULTS_LOADING = "HOMERESULTS_LOADING";
export const HOMERESULTS_FAILED = "HOMERESULTS_FAILED";
